@startuml mascota


package Mascotas{
    class Gato{
        -salud:Salud
        +Dormir(Cama)
        +Jugar(Hilaza)
        +Desechar(Arenero)
        +Comer(Croquetas)
    }
    class Perro{
        -salud:Salud
        -collar:Collar
        +Dormir(Cama)
        +Jugar(Pelota)
        +Desechar(Parque)
        +Comer(Hueso)
    }
    class Pez{
        -salud:Salud
        +Desechar(Pecera)
        +Comer(Alga)
    }
    class Mascota
    class Salud
    class Pecera
    class Collar
}

package Alimentos {
    class Carne
    class Hueso 
    class Alga
class Alimento
}

package Baños {
    class Arenero
    class Parque 
    class Baño 
}

package Juguetes{
    class Pelota
    class Hilaza
    class Juguete
}
package Bedroom{
    class Dormitorio
    class Cama
}

Alimento "1"--o "1" Mascota
Mascota "1" o--"1" Juguete
Pelota--|> Juguete
Gato--|>Mascota
Perro--|>Mascota
Pez --|>Mascota
Perro "1" o-- "*" Cama
Gato "1" o-- "*" Cama
Dormitorio "1" *-- "1" Cama
Gato "1" o-- "1" Hilaza
Hilaza --|> Juguete
Pez "1" o-- "1" Alga
Alga --|> Alimento
Baño "1" *-- "1" Parque
Perro "1" o-- "1" Parque
Baño "1" *-- "2" Arenero
Arenero "1" --o "1" Gato
Perro "1" *-- "1" Collar
Perro "1" *-- "*" Salud
Gato "1" *-- "*" Salud
Pez "1" *-- "*" Salud
Perro "1" o-- "1" Hueso
Pez "1" o-- "1" Pecera
Perro "1" o-- "1" Pelota
Gato "1" o-- "1" Carne

@enduml